### ISSUE TITLE
计划管理功能完善

### ISSUE THREAD

**Issue by doublemoyu** [q19980722/Chrome-ext-Ava#2]
无法进行对已经保存的计划的修改，计划管理选项只有删除功能有些单一

**Comment by q19980722** [comment]
emmm，因为目前计划那一页面里没有显示历史记录，所以想要编辑的话可以删除原有的，再添加新的。之后如果计划界面显示历史记录，会同步更新编辑功能。
整个项目因为时间关系，做不完了，临时砍掉了很多功能。
