### ISSUE TITLE
是否可以打包发布为浏览器插件

### ISSUE THREAD

**Issue by Opdoop** [q19980722/Chrome-ext-Ava#3]
不是很懂实现和兼容问题，看隔壁的 [Asoul桌宠](https://www.bilibili.com/video/BV1744y1u7ym) 作为插件推广安装很方便的样子。不知道插件小向晚能否打包发布为浏览器插件

**Comment by q19980722** [comment]
可以的，不过谷歌会收费5美元，这种安装方式也并不复杂，虽然可能推广的效果不好。 不过这种本来就是圈内人的东西，也没指望真的出圈，所以就没有做打包。

**Comment by Opdoop** [comment]
是否有捐赠链接，我可以赞助 5 美元，期待上架❤

**Comment by q19980722** [comment]
> 是否有捐赠链接，我可以赞助 5 美元，期待上架❤

感谢您的喜爱与支持！ 不过，我刚刚去仔细了解了一下，支付不仅是钱的问题，还需要一张visa的信用卡，我没有，所以我没办法注册成为谷歌开发者，因此也就暂时无法上架了。  之后有时间的话我再去看看有没有解决办法吧！
